name: 'Reviewdog / Stylelint'

description: 'Lint code using stylelint'

inputs:
  github-token:
    description: 'Github token'
    required: true

runs:
  using: 'composite'

  steps:
    - name: Reset permissions
      shell: bash
      run: sudo chown -R $USER:$USER $GITHUB_WORKSPACE

    - uses: actions/checkout@v2

    - name: Read .nvmrc
      shell: bash
      id: nvm
      run: echo "##[set-output name=NVMRC;]$(cat .nvmrc)"

    - name: Use Node.js ${{ steps.nvm.outputs.NVMRC }}
      uses: actions/setup-node@v2-beta
      with:
        node-version: "${{ steps.nvm.outputs.NVMRC }}"

    - name: Install yarn
      shell: bash
      run: npm install -g yarn

    - name: Install dependencies
      shell: bash
      run: yarn install --pure-lockfile
      env:
        CI: true

    - name: Reset permissions
      shell: bash
      run: sudo chown -R root:root $GITHUB_WORKSPACE
      
    - name: Try a fix
      shell: bash
      run: git config --global --add safe.directory "$GITHUB_WORKSPACE" || exit 1

    - name: Stylelint
      uses: reviewdog/action-stylelint@v1
      with:
        github_token: ${{ inputs.github-token }}
        reporter: github-pr-review
        stylelint_input: './resources/**/*.{scss,vue}'
        

    - name: Reset permissions
      shell: bash
      run: sudo chown -R $USER:$USER $GITHUB_WORKSPACE
