name: 'Reviewdog / Eslint'

description: 'Lint code using eslint'

inputs:
  ignore-path:
    description: 'Eslint ignore file path'
    default: '.gitignore'

runs:
  using: 'composite'

  steps:
    - name: Reset permissions
      shell: bash
      run: sudo chown -R $USER:$USER $GITHUB_WORKSPACE

    - uses: actions/checkout@v3

    - name: Read .nvmrc
      id: nvm
      shell: bash
      run: |
        version=$(cat .nvmrc)
        echo "NVMRC=$version" >> $GITHUB_OUTPUT

    - name: Use Node.js ${{ steps.nvm.outputs.NVMRC }}
      uses: actions/setup-node@v3
      with:
        node-version: "${{ steps.nvm.outputs.NVMRC }}"

    - name: Install yarn
      shell: bash
      run: npm install -g yarn

    - name: Reset permissions
      shell: bash
      run: sudo chown -R $USER:$USER $GITHUB_WORKSPACE

    - name: Install dependencies
      shell: bash
      run: yarn install --pure-lockfile
      env:
        CI: true

#     - name: Reset permissions
#       shell: bash
#       run: sudo chown -R root:root $GITHUB_WORKSPACE

    - name: Eslint
      uses: reviewdog/action-eslint@v1
      with:
        reporter: github-pr-review # Change reporter.
        eslint_flags: '--ext .js,.vue --ignore-path ${{ inputs.ignore-path }} .'

    - name: Reset permissions
      shell: bash
      run: sudo chown -R $USER:$USER $GITHUB_WORKSPACE
