name: 'Reviewdog / Vue TSC'

description: 'Lint code using vue-tsc'

runs:
  using: 'composite'

  steps:
    - uses: reviewdog/action-setup@v1
      with:
        reviewdog_version: v0.17.1

    - run: $GITHUB_ACTION_PATH/script.sh
      shell: bash
      env:
        INPUT_GITHUB_TOKEN: ${{ inputs.github_token }}
        INPUT_WORKDIR: ${{ inputs.workdir }}
        INPUT_LEVEL: ${{ inputs.level }}
        INPUT_REPORTER: ${{ inputs.reporter }}
        INPUT_FILTER_MODE: ${{ inputs.filter_mode }}
        INPUT_FAIL_ON_ERROR: ${{ inputs.fail_on_error }}
        INPUT_REVIEWDOG_FLAGS: ${{ inputs.reviewdog_flags }}
        INPUT_TOOL_NAME: ${{ inputs.tool_name }}
        INPUT_TSC_FLAGS: ${{ inputs.tsc_flags }}
