name: 'Visual Regression Testing'

description: 'Run visual regression testing'

inputs:
  aws-access-key-id:
    description: 'AWS access key id'
    required: true
  aws-secret-access-key:
    description: 'AWS secret access key'
    required: true

runs:
  using: 'composite'

  steps:
    - name: Check if VRT enabled
      id: vrt_enabled
      shell: bash
      run: |
        vrtClientId=`echo $(jq -r '.plugins."reg-notify-github-plugin".clientId' <<< "$(cat regconfig.json)")`
        if [[ $vrtClientId != "" ]]; then
          echo "runVrt=true" >> $GITHUB_OUTPUT
          echo "VRT Enabled"
        else
          echo "VRT Not enabled"
        fi

#    - name: workaround for detached HEAD
#      if: steps.vrt_enabled.outputs.runVrt
#      shell: bash
#      run: git checkout origin/${{ github.event.pull_request.head.ref }} && git pull

    - name: Install dependencies
      shell: bash
      run: yarn install --frozen-lockfile

    - name: Build storybook
      if: steps.vrt_enabled.outputs.runVrt
      shell: bash
      run: yarn storybook:build

    - name: create the current snapshot
      if: steps.vrt_enabled.outputs.runVrt
      shell: bash
      run: yarn storycap

    - name: Run Reg-suit (pull request)
      if: steps.vrt_enabled.outputs.runVrt && github.event_name == 'pull_request'
      shell: bash
      env:
        AWS_ACCESS_KEY_ID: ${{ inputs.aws-access-key-id }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.aws-secret-access-key }}
        BASE_SHA: ${{ github.event.pull_request.base.sha }}
        HEAD_SHA: ${{ github.event.pull_request.head.sha }}
      run: yarn run reg-suit run

    - name: Run Reg-suit (push)
      if: steps.vrt_enabled.outputs.runVrt && github.event_name == 'push'
      shell: bash
      env:
        AWS_ACCESS_KEY_ID: ${{ inputs.aws-access-key-id }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.aws-secret-access-key }}
      run: |
        node ${{ github.action_path }}/generate-reg-config.js "${{ github.workspace }}"
        yarn run reg-suit run --config=regconfig-push.json
