name: Visual Regression Testing

description: Run visual regression testing

inputs:
  aws-access-key-id:
    description: AWS access key id
    required: true
  aws-secret-access-key:
    description: AWS secret access key
    required: true

runs:
  using: composite

  steps:
    - name: Reset permissions
      shell: bash
      run: sudo chown -R $USER:$USER $GITHUB_WORKSPACE

    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install Chrome
      id: chrome
      uses: browser-actions/setup-chrome@facf10a55b9caf92e0cc749b4f82bf8220989148 # v1.7.2
      with:
        chrome-version: 127

    - name: Read .nvmrc
      shell: bash
      id: nvm
      run: |
        version=$(cat .nvmrc)
        echo "NVMRC=$version" >> $GITHUB_OUTPUT

    - name: Use Node.js ${{ steps.nvm.outputs.NVMRC }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ steps.nvm.outputs.NVMRC }}

    - name: Install yarn
      shell: bash
      run: npm install -g yarn

    - name: workaround for detached HEAD
      shell: bash
      run: git checkout ${{ github.event.pull_request.head.ref }} && git pull

    - name: Reset permissions
      shell: bash
      run: sudo chown -R $USER:$USER $GITHUB_WORKSPACE

    - name: Install dependencies
      shell: bash
      run: yarn install --pure-lockfile
      env:
        CI: true

    - name: Build storybook
      shell: bash
      run: yarn storybook:build

    - name: Create the current snapshots
      shell: bash
      run: yarn storycap --chromiumPath ${{ steps.chrome.outputs.chrome-path }}

    - name: Run Reg-suit (pull request)
      if: github.event_name == 'pull_request'
      shell: bash
      env:
        AWS_ACCESS_KEY_ID: ${{ inputs.aws-access-key-id }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.aws-secret-access-key }}
        BASE_SHA: ${{ github.event.pull_request.base.sha }}
        HEAD_SHA: ${{ github.event.pull_request.head.sha }}
      run: yarn run reg-suit run

    - name: Run Reg-suit (push)
      if: github.event_name == 'push'
      shell: bash
      env:
        AWS_ACCESS_KEY_ID: ${{ inputs.aws-access-key-id }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.aws-secret-access-key }}
      run: |
        node ${{ github.action_path }}/generate-reg-config.js "${{ github.workspace }}"
        yarn run reg-suit run --config=regconfig-push.json
